spring.application.name=Trainee
spring.datasource.url=jdbc:postgresql://localhost:5432/Traineedb
spring.datasource.username=postgres
spring.datasource.password=945845

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true