spring.application.name=TraineeAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeDb
spring.datasource.username=postgres
spring.datasource.password=945845

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8087