server.port=8761
spring.application.name=eureka-server

# Fix for the error - disable config server for Eureka
spring.cloud.config.enabled=false

# Don't register itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0