server.port=8888
spring.application.name=config-server

# Your GitHub config repo
spring.cloud.config.server.git.uri=https://github.com/cipher-sphere/clipkart-config
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.force-pull=true

# Eureka (comment this out until Eureka Server is running)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true